[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
name = "parachain-info"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false, branch = "shamb0/test/polkadot-v0.9.13" }
frame-system = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false, branch = "shamb0/test/polkadot-v0.9.13" }

cumulus-primitives-core = { path = "../../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
]
