[package]
name = "pallet-asset-tx-payment"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
description = "pallet to manage transaction payments in assets"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
frame-support = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
frame-system = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
pallet-transaction-payment = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
sp-core = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
sp-io = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
sp-runtime = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }
sp-std = { git = "https://github.com/rajesh-nodle/substrate.git", default-features = false , branch = "shamb0/test/polkadot-v0.9.13" }

# Other dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

[dev-dependencies]
smallvec = "1.4.1"
serde_json = "1.0.41"

pallet-assets = { git = "https://github.com/rajesh-nodle/substrate.git", branch = "shamb0/test/polkadot-v0.9.13" }
pallet-authorship = { git = "https://github.com/rajesh-nodle/substrate.git", branch = "shamb0/test/polkadot-v0.9.13" }
pallet-balances = { git = "https://github.com/rajesh-nodle/substrate.git", branch = "shamb0/test/polkadot-v0.9.13" }
sp-storage = { git = "https://github.com/rajesh-nodle/substrate.git", branch = "shamb0/test/polkadot-v0.9.13" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-core/std",
	"pallet-transaction-payment/std",
]
try-runtime = ["frame-support/try-runtime"]
